### ISSUE TITLE
Get players back from Adventure Guild world

### ISSUE THREAD

**Issue by hernikplays** [MagmaGuy/EliteMobs#18]
Hey, I'm using EliteMobs on 1.14.4 and when players teleport to the Adventurers Guild world using the `/ag` command, they cannot get back to their previous location, as there is no command for that, not even Essentials's `back` command can't do that. Can you please add a command that would teleport them back to their previous location?

**Comment by MagmaGuy** [comment]
It's planned, the main reason why it's not implemented yet is because each server has their own method of doing teleportations. The portal will take the player to the last known location, though the ability to have the player teleport to spawn or some warp point will still be necessary for when no previous valid locations can be found.
