### ISSUE TITLE
[Feature Request] Return teleport from Adventurers Guild

### ISSUE THREAD

**Issue by bundabrg** [MagmaGuy/EliteMobs#39]
As the AG is another world I'd suggest saving the world + location when a player uses the /ag then sending them back to that location if the command is executed in the AG. This will stop players from using it as a way to fast travel the map (which most other plugins like warp, home etc will add). Perhaps if the player quits whilst in the AG they should also be returned as well to save having to store the information.

**Comment by MagmaGuy** [comment]
This is planned, but it's not a very high priority project because servers tend to drastically vary in how they like to have teleports handled, and no system that I could ever come up with will fully incorporate what people want for teleporting. It also adds a number of potentially problematic situations, such as players being able to go back to a place that is supposed to close after an amount of time, such as a dungeon or arena.

The vast majority of servers out there already has a teleport system in place, which is why I haven't really spent too much time working on a solution for this one yet.
