### ISSUE TITLE
1.8 Compitability?

### ISSUE THREAD

**Issue by ElementalShadow** [MagmaGuy/EliteMobs#4]
Please can you make this plugin compitabile with 1.8 version of mc? That can be very big success almost everybody are using 1.8 version.

**Comment by MagmaGuy** [comment]
1.8 came out in 2014.

It's currently 2017.

I have no plans to do backward compatibility before 2020, and even then I'm not sure I'll do it.

Even if I ever get around to actually doing it, 1.8 will be 6 years old by then. Minecraft will probably have seen 11 major updates since. That would be like me supporting servers that still run beta versions right now.

Unless someone else wants this done so much they either 
A) pay me very handsomely to do it (I really don't want to do it so it will cost a lot, $750) or 
B) do it themselves
it is not going to happen.

Hell, even if I were to do backwards compatibility right now, I would not go past 1.9. I have a long list of reasons why I don't want to do this, which I'll happily express if someone wishes to talk about it over Discord.
