### ISSUE TITLE
General issues

### ISSUE THREAD

**Issue by 71Zombie** [MagmaGuy/EliteMobs#43]
Great plugin, but has some major issues. Every once in a while the NPCs on Adventures Guild will simply disappear, forcing me to reload the plugin to fix the issue. Even sometimes with the NPCs spawned, I will still have to reload the plugin to fix them. Now on one of the dungeons I have configured a disguise. I will have to reload the plugin again to fix the NPCs. This plugin also tends to bring down the server TPS, I would recommend making it optimized for paperMC. I highly doubt this is a configuration error because I see no errors in console about this whatsoever. I can confirm that there are no incompatible plugins running alongside with this.

**Comment by MagmaGuy** [comment]
I am aware of at least most of these issues, though it causing TPS issues is news to me. If you could provide timings that'd be great. I use it on a paper server and I get nothing but 20tps with all dungeons loaded, and since my entire development and live environment are Paper-based, I'd say it's optimized for Paper.

I am already in the middle of a full rewrite of some of the core components that are problematic, and am hoping that testers will be testing the first few dev builds this weekend.

 It would've been significantly faster to patch the current issues out, but I have opted to stop applying band-aid fixes and go straight for a system that is built to be more efficient, reliable and scalable at its core. Unfortunately, that means dozens of hours of work between planning, implementing, refactoring code and testing.

**Comment by MagmaGuy** [comment]
Oh wait if you mean doing a reload causes TPS issues that's 100% normal, it's not meant to be run constantly and it actually does a full reset of EliteMobs during runtime. Not sure if I misread that.

**Comment by 71Zombie** [comment]
Thank you for your response. Here are the timings- https://timings.aikar.co/?id=f6c74e9ff7004d8fa04579cf28946985

**Comment by 71Zombie** [comment]
Interestingly, after reloading the plugin after the timings report it raised the TPS back up to 20 again

**Comment by MagmaGuy** [comment]
These issues should now be resolved.
