### ISSUE TITLE
events.yml needs more options.

### ISSUE THREAD

**Issue by FrozenBeard** [MagmaGuy/EliteMobs#9]
Severely lacking options for "Boss" event mobs.

- There is no message for the Kraken to players option
- You cannot set what specific items Boss/Event Elites drop, its just tied to one.
- You cannot change the type of event a boss mob is spawned in, fishing etc, and there are no variables to fine tune each, I have had to disable most of them as players can just farm them and get stacks and stacks of the custom items.
- There needs to be a universal set of settings for each Boss mob that are the same, consistent settings for each event boss mob

**Comment by MagmaGuy** [comment]
1) action bosses currently have no messages as the events are meant to only really affect the person that they happen to. I've been toying with the idea of adding a direct message to those players, just have not gotten around to actually implementing it.



2) that's 100% intentional. Unique items for unique bosses which are thematically tied. You can, however, edit the drop itself to be different if it doesn't work for you. Further customization options are very much out of the scope of what I originally intended to do here.

 3) again, these are thematic. If players are abusing then, I recommend increasing the rarity of the event, that's how I balanced it out. As a matter of fact, since the last release, I've made it so the unique items are dynamic so low level action events are less abusable. 

4) I agree that the customization options can be expanded upon. I usually add more options when they are requested, if something is missing for you personally it's probably because you were the first one to express the need for that config option. Feel free to drop some specific baseline requests here or, even better, in my discord server.

**Comment by FrozenBeard** [comment]
1. When a boss mob spawns and a global message is broadcast, this does a few things, it allows other people to help out/steal the kill, it teaches new players that boss mobs actually spawn without having it spawn on them and them being completely perplexed by what is happening. Global broadcast messages are a must for EVENTS. If its an event its server wide event, not player based as anyone can join in.

2. So I cant even remove an item from being dropped is what you are saying? A better option would be to have each Boss Mob link to a indented "section" not sure what you call this in YAML which allows adding as many or little item drops as you want, and just loop through, each droprate is per item, so you could have 1 or 2 or whatever drop randomly.

3. Specifically let me explain, You have breaking all ore blocks, players instantly figured this out instantly and just used Silk Touch in their own environment to farm the mob, Boss mobs should NOT be allowed to be farmed. I was unable to adjust what blocks broken caused the event to spawn on, and why Silk Touch is allowed is beyond me.

4. I have 100 ideas, but I start with fixing what is broken first. This is my first time extensively using Elite Mobs for my Halloween event, and have encountered quite a few issues.

**Comment by MagmaGuy** [comment]
1) Action events are not meant to be server-wide, they are not calibrated to be fought against by multiple users and they do not drop multiple items. They're modeled after the random events runescape had back when I was playing. They are meant to be surprising to new players. More than anything else, they are there to break up the monotony of repeating the same task hundreds of times. If you don't like this concept of events, you are more than welcome to disable them.

2) I am 99% certain I added ways to turn off unique items individually and as a whole. I am not interested at this time - or at any time - to do more in-depth customization of event bosses. This plugin is meant to offer dynamic, prebuilt mobs that you can tweak as an admin - not custom mobs that drop custom amounts of custom items at custom intervals. There is already a plugin that does this, and it's called MythicMobs. EliteMobs is not MythicMobs, nor does it aim to become it.

3) Silk touch is allowed simply because players hadn't figured out the exact requirements to spawn Balrogs so far and also because it was super fast to add and my free time is not unlimited. Since you've reported that they've figured it out, I'll be adding different filters from now on.

4) I won't add 100% of your 100 ideas, but I'll certainly give it a fair jab. Just keep in mind that this is a plugin that is dynamic first and customizable second.

**Comment by FrozenBeard** [comment]
1. It literally states "how many players are around" figures out an elite level, its written as a feature on the plugin page, it should be named "PlayerEvents" as the word Events means a global event and most people expect a Boss mob to be fought by multiple people, thats why they are on minecraft server and not playing single player, to play with others! I like the idea of Player based events and Global events, this really isn't clear anywhere especially with what you have named it all.

2. It wasn't related to MythicMobs, I've used MythicMobs in great depth for events, and needed something faster for events, im literally giving you feedback of the issues we have encountered with the plugin, dont take offence to it.

3. The silk touch event spawning a boss is absurd, I also got sent this message saying 10s of players were using this method to farm him.
> if you put a stack of coal blocks or logs in your off-hand, and have a fast mining pick/axe in the main hand, you can hold down both mouse buttons and it will break the blocks pretty fast

**Comment by MagmaGuy** [comment]
1) I don't call them PlayerEvents because those are a thing in the spigot API. I call them action events because they are triggered by an action at an individual level. I'll make extra sure to explain the difference between ActionEvents and Timed Events in future documentation.

2) I'm not taking offense but I need to be firm about it. I frequently get requests for unmanageable levels of customization for the volume of different features that I want to be able to offer. I would rather offer 100 different features and have users turn 50 of those off instead of offering 20 features that 100% of people will use. Customization is incidental here; this is a plug-in for my network and personal entertainment first and an open source, public, customizable plug-in second. Just want to be extra clear where I stand as far as the scope of this plugin goes.

3) :) that's hilarious. Yeah it will be fixed on the next dev build.
